(() => {
const $=s=>document.querySelector(s),KEY={h:'ylkx_history_v1',f:'ylkx_favorites_v1'};
const S={records:[],manifest:null,laws:[],hits:[],question:'',answer:null,facts:[]};
const E={form:$('#searchForm'),q:$('#question'),dept:$('#department'),submit:$('#submitButton'),answer:$('#answer'),conclusion:$('#conclusion'),summary:$('#summary'),conditions:$('#conditions'),actions:$('#actions'),exceptions:$('#exceptions'),citations:$('#citations'),tags:$('#queryTags'),count:$('#resultCount'),results:$('#results'),status:$('#dataStatus'),template:$('#resultTemplate'),clarify:$('#clarifyPanel'),clarifyQuestion:$('#clarifyQuestion'),clarifyOptions:$('#clarifyOptions'),lawList:$('#lawList'),lawSearch:$('#lawSearch'),lawDialog:$('#lawDialog'),savedDialog:$('#savedDialog')};
const synonyms=new Map([['退货',['消费者','经营者','七日','网络购买','解除合同']],['网购',['消费者','网络购买','七日','退货']],['辞退',['劳动合同','解除','经济补偿','用人单位']],['欠薪',['工资','劳动报酬','支付','用人单位']],['押金',['租赁','返还','合同']],['隐私',['隐私权','个人信息','泄露']],['泄露',['个人信息','隐私权','处理者']],['离婚',['婚姻','夫妻','财产','子女']],['校园欺凌',['未成年人','学校','保护']],['赡养',['父母','成年子女','赡养义务']],['被骗',['诈骗','欺诈','撤销']],['合同',['合同','履行']],['违约',['民法典','违约责任','继续履行','补救措施','赔偿损失']],['社保',['社会保险','用人单位','缴费']],['著作权',['作品','权利人','许可']],['商标',['注册商标','侵权']]]);
const stop=new Set(['可以','怎么','怎样','是否','什么','需要','如果','应该','能够','有关','一个','哪些','如何','了吗','怎么办']);
const topics=[['劳动用工','工资、辞退与经济补偿','公司解除劳动合同需要支付经济补偿吗？'],['消费维权','退货、退款与经营者责任','网购商品不满意可以退货吗？'],['婚姻家庭','婚姻、监护与家庭责任','未成年人的监护人有哪些责任？'],['合同交易','履行、违约与损失赔偿','合同违约需要承担什么责任？'],['个人信息','隐私、授权与信息泄露','个人信息被他人泄露怎么办？'],['未成年人','家庭、学校与网络保护','学校应当如何保护未成年人？'],['社会保障','社保缴纳与待遇保障','单位不缴纳社会保险怎么办？'],['知识产权','著作权、商标与侵权','未经许可使用他人作品有什么责任？']];
const esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const store=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),rid=x=>`${x.n}|${x.a}|${x.v||''}`;

Promise.all([fetch('data/manifest.json').then(r=>r.json()),fetch('data/legal-index.json').then(r=>r.json())]).then(([m,r])=>{S.manifest=m;S.records=r;E.submit.disabled=false;E.status.textContent=`知识库已就绪 · ${r.length.toLocaleString('zh-CN')} 条适用记录 · 数据截至 ${m.asOf}`;$('#dialogRecords').textContent=r.length.toLocaleString('zh-CN');$('#dialogDocs').textContent=`${m.documents} 个`;Object.keys(m.departments).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=`${n}（${m.departments[n].toLocaleString('zh-CN')}）`;E.dept.append(o)});buildLaws();renderLaws();dashboard();renderSaved()}).catch(()=>E.status.textContent='知识库装载失败，请刷新页面后重试');

function terms(q){const n=q.replace(/[，。！？、；：,.!?;:\s]/g,''),a=new Set;for(let l=Math.min(6,n.length);l>=2;l--){for(let i=0;i<=n.length-l;i++){const p=n.slice(i,i+l);if(l===2||synonyms.has(p))a.add(p)}if(a.size>22)break}[...a].forEach(x=>{if(stop.has(x))a.delete(x)});synonyms.forEach((v,k)=>{if(n.includes(k))v.forEach(x=>a.add(x))});return[...a].slice(0,32)}
function search(q,d=''){const ts=terms(q),all=[],compact=q.replace(/\s+/g,'');for(const x of S.records){if(d&&x.d!==d)continue;let score=0,topic=x.k.join(' ');if(x.t.includes(compact))score+=28;for(const t of ts){if(x.n.includes(t))score+=8;if(topic.includes(t))score+=5;if(x.c.includes(t))score+=3;if(x.t.includes(t))score+=t.length>=4?4:1.7}if(/合同|违约/.test(q)&&!/劳动|公司|单位|员工|工资/.test(q)&&x.n.includes('劳动合同法'))score-=14;if(/网购|退货|消费者/.test(q)){if(x.n.includes('消费者权益保护法'))score+=24;if(x.n.includes('进出口商品检验法'))score-=24}if(score>=3.4)all.push({item:x,score})}all.sort((a,b)=>b.score-a.score);const max=all[0]?.score||0;if(max<8)return{hits:[],terms:ts.slice(0,8)};const per=new Map,hits=[];for(const h of all){if(h.score<Math.max(8,max*.3))break;const c=per.get(h.item.n)||0;if(c>=4)continue;per.set(h.item.n,c+1);hits.push(h);if(hits.length===8)break}return{hits,terms:ts.filter(t=>t.length>=2).slice(0,8)}}
function highlight(text,ts){let safe=esc(text);ts.filter(t=>t.length>=2).slice(0,5).forEach(t=>{const x=esc(t).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');safe=safe.replace(new RegExp(x,'g'),m=>`<mark>${m}</mark>`)});return safe}

const rules=[
[/网购|网络购买|无理由退货/,/退货|退款|不满意/,{conclusion:'一般可以，但要同时满足购买方式、期限和商品状态等条件。网络购买商品通常享有七日无理由退货权。',conditions:['属于网络、电视、电话或邮购等远程购买','原则上自收到商品之日起未超过七日','退回商品能够保持完好'],actions:['保存订单、支付记录和收货日期','在平台或商家页面提交退货申请','与商家确认退货地址、运费和退款时间'],exceptions:'定作、鲜活易腐、在线下载或已拆封的数字化商品、已交付的报纸期刊等通常不适用七日无理由退货；质量问题可另按质量责任处理。',clarify:['购买与商品情况',['网络平台购买','收货未满7日','商品已拆封使用','商品有质量问题']]}],
[/解除|辞退|裁员|终止/,/劳动合同|公司|单位|员工|经济补偿/,{conclusion:'不一定。是否支付经济补偿，主要取决于解除主体、解除原因及程序是否合法。',conditions:['属于协商解除、非过失性解除或经济性裁员等法定情形','工作年限和月工资可以确定','解除决定及送达过程有相应证据'],actions:['保存劳动合同、工资流水、考勤和解除通知','要求单位书面说明解除理由与补偿计算','无法协商时在法定期限内申请劳动仲裁'],exceptions:'劳动者因严重过错被依法解除时通常不适用经济补偿；违法解除可能涉及赔偿金。',clarify:['解除劳动合同的情况',['单位主动解除','双方协商解除','员工存在过错','单位未说明理由']]}],
[/个人信息|隐私/,/泄露|侵害|非法|滥用|公开/,{conclusion:'可以要求停止不当处理、删除或更正信息并采取补救措施；造成损害的，可依法主张赔偿。',conditions:['能够识别实施处理或泄露行为的主体','处理行为缺乏合法依据或超出必要范围','损失或风险与该行为具有联系'],actions:['截图、录屏并保存通知和聊天记录','向平台或处理者提出删除、停止处理等请求','必要时向主管部门投诉或依法起诉'],exceptions:'合法、正当、必要且有明确依据的信息处理可能不构成侵害；赔偿仍需结合损失与过错判断。',clarify:['信息泄露的情况',['平台或公司泄露','个人擅自公开','已经造成损失','仅发现异常风险']]}],
[/未成年|孩子|子女/,/监护|父母|责任|义务/,{conclusion:'父母原则上是未成年子女的监护人，负有抚养、教育、保护并维护其合法权益的职责。',conditions:['当事人为未成年人','父母具备履行监护职责的条件','事项与未成年人的人身、财产或其他权益有关'],actions:['以最有利于未成年人的方式作出决定','妥善管理财产并保留重大事项记录','权益受侵害时及时制止并寻求帮助'],exceptions:'父母死亡、无监护能力或严重侵害权益时，监护资格和顺位可能依法调整。'}],
[/工资|薪资|薪水|欠薪/,/拖欠|不发|克扣|支付/,{conclusion:'用人单位原则上应及时、足额支付劳动报酬，不得无故拖欠或克扣。',conditions:['双方存在劳动关系','工资标准和工作期间能够证明','单位未按约定或规定支付'],actions:['保存合同、考勤、工资条和银行流水','向单位书面催告并固定沟通证据','向劳动监察投诉或申请劳动仲裁'],exceptions:'具体金额还可能受绩效规则、请假情况和合法扣除项目影响。'}],
[/合同/,/违约|不履行|不符合约定/,{conclusion:'一般需要承担违约责任。守约方可结合情况要求继续履行、采取补救措施或赔偿损失。',conditions:['存在有效合同义务','一方未履行或履行不符合约定','违约与损失之间存在联系'],actions:['核对合同义务、期限和违约条款','书面催告履行并保存回复','整理损失凭证后协商、仲裁或诉讼'],exceptions:'不可抗力、对方先违约、有效免责条款或继续履行已不可能等情形会影响责任。'}]
];
function core(x,ts){const ss=x.t.split(/(?<=[。！？；])/).map(s=>s.trim()).filter(s=>s.length>=8&&s.length<=180);return(ss.map(s=>{let n=/应当|有权|不得|可以|承担|负责|必须|享有/.test(s)?4:0;ts.forEach(t=>{if(s.includes(t))n+=t.length>=4?3:1});return{s,n}}).sort((a,b)=>b.n-a.n)[0]?.s||x.t.slice(0,160)).replace(/\s+/g,' ').slice(0,190)}
function makeAnswer(q,r){const m=rules.find(([a,b])=>a.test(q)&&b.test(q));if(m)return m[2];const x=r.hits[0]?.item;if(!x)return{conclusion:'现有证据不足，暂时不能形成可靠结论。',conditions:['问题需与知识库中的具体法律事项相关','请说明行为主体、发生了什么以及希望确认的权利或责任'],actions:['补充具体事实后重新提问','尝试使用“事项＋权利或义务”的表达方式'],exceptions:'本平台不会在缺少相关条文依据时推测答案。'};return{conclusion:`初步来看，该问题主要受《${x.n}》${x.a}调整。`,conditions:[core(x,r.terms),'行为、主体身份和时间应符合该条适用范围'],actions:['核对下方条文原文与版本信息','补充争议主体、时间和证据后再次检索','重大事项向专业人士进一步咨询'],exceptions:'条文是否最终适用，仍需结合完整事实、特别规定和程序要求判断。',clarify:['影响判断的事实',['我是权利受影响的一方','对方是企业或单位','有书面合同或记录','已经造成实际损失']]}}
function list(el,a){el.innerHTML='';a.forEach(x=>{const li=document.createElement('li');li.textContent=x;el.append(li)})}
function showClarify(c){E.clarifyOptions.innerHTML='';S.facts=[];if(!c){E.clarify.hidden=true;return}E.clarify.hidden=false;E.clarifyQuestion.textContent=`请补充${c[0]}：`;c[1].forEach(v=>{const b=document.createElement('button');b.type='button';b.textContent=v;b.onclick=()=>{b.classList.toggle('selected');S.facts=b.classList.contains('selected')?[...S.facts,v]:S.facts.filter(x=>x!==v)};E.clarifyOptions.append(b)});const go=document.createElement('button');go.type='button';go.className='clarify-submit';go.textContent='带补充信息重新判断';go.onclick=()=>{if(!S.facts.length)return;const q=`${S.question}（补充：${S.facts.join('、')}）`;E.q.value=q;run(q,E.dept.value)};E.clarifyOptions.append(go)}
function render(q,r){S.question=q;S.hits=r.hits;E.answer.hidden=false;E.results.innerHTML='';E.tags.innerHTML='';E.citations.innerHTML='';const a=makeAnswer(q,r);S.answer=a;E.conclusion.textContent=a.conclusion;list(E.conditions,a.conditions);list(E.actions,a.actions);E.exceptions.textContent=a.exceptions;showClarify(a.clarify);if(!r.hits.length){E.summary.textContent='当前适用知识库中没有找到足够相关的条文，因此系统停止生成具体法律判断。';E.count.textContent='证据不足 · 未展示推测性结果';setTimeout(()=>E.answer.scrollIntoView({behavior:'smooth'}),40);return}const laws=[...new Set(r.hits.map(h=>h.item.n))];E.summary.textContent=`围绕“${q}”，已筛选出 ${r.hits.length} 条相关依据。最直接的依据来自《${laws[0]}》。`;r.terms.forEach(t=>{const s=document.createElement('span');s.textContent=t;E.tags.append(s)});E.count.textContent=`显示 ${r.hits.length} 条 · 涉及 ${laws.length} 个文件`;const favs=store(KEY.f);r.hits.forEach(({item},i)=>{const card=E.template.content.firstElementChild.cloneNode(true);card.id=`evidence-${i+1}`;card.querySelector('.department-pill').textContent=item.d;card.querySelector('.score-label').textContent=`相关依据 ${String(i+1).padStart(2,'0')}`;card.querySelector('h3').textContent=`《${item.n}》${item.a}`;card.querySelector('.chapter').textContent=item.c||'未标注章节';card.querySelector('.provision').innerHTML=highlight(item.t,r.terms);card.querySelector('.dates').textContent=`${item.p} · 版本 ${item.v||'未标注'}`;const ex=card.querySelector('.expand-button');ex.onclick=()=>{const o=card.classList.toggle('expanded');ex.textContent=o?'收起原文':'展开原文'};const f=card.querySelector('.favorite-button'),id=rid(item);f.textContent=favs.includes(id)?'已收藏':'收藏';f.classList.toggle('active',favs.includes(id));f.onclick=()=>toggleFav(item,f);E.results.append(card);const cite=document.createElement('button');cite.type='button';cite.textContent=`[${i+1}]《${item.n}》${item.a}`;cite.onclick=()=>{card.scrollIntoView({behavior:'smooth',block:'center'});card.classList.add('flash');setTimeout(()=>card.classList.remove('flash'),1800)};E.citations.append(cite)});setTimeout(()=>E.answer.scrollIntoView({behavior:'smooth',block:'start'}),40)}
function history(q){const a=store(KEY.h).filter(x=>x!==q);a.unshift(q);save(KEY.h,a.slice(0,20));renderSaved()}
function run(q,d=''){q=String(q||'').trim();if(!q||!S.records.length)return{total:0};const r=search(q,d);render(q,r);history(q);return{conclusion:S.answer.conclusion,conditions:S.answer.conditions,actions:S.answer.actions,exceptions:S.answer.exceptions,total:r.hits.length,displayed:r.hits.map(x=>({law_name:x.item.n,article_no:x.item.a,text:x.item.t,version_date:x.item.v}))}}
function toggleFav(x,b){let a=store(KEY.f),remove=a.includes(rid(x));a=remove?a.filter(v=>v!==rid(x)):[rid(x),...a];save(KEY.f,a);b.textContent=remove?'收藏':'已收藏';b.classList.toggle('active',!remove);renderSaved()}
function renderSaved(){const h=$('#historyList'),f=$('#favoriteList');if(!h||!f)return;h.innerHTML='';f.innerHTML='';const hs=store(KEY.h);if(!hs.length)h.innerHTML='<p class="empty-state">还没有检索记录</p>';hs.forEach(q=>{const b=document.createElement('button');b.type='button';b.textContent=q;b.onclick=()=>{E.savedDialog.close();E.q.value=q;run(q,E.dept.value)};h.append(b)});const map=new Map(S.records.map(x=>[rid(x),x])),xs=store(KEY.f).map(id=>map.get(id)).filter(Boolean);if(!xs.length)f.innerHTML='<p class="empty-state">还没有收藏条文</p>';xs.forEach(x=>{const d=document.createElement('div');d.className='saved-item';d.innerHTML=`<strong>《${esc(x.n)}》${esc(x.a)}</strong><p>${esc(x.t.slice(0,100))}${x.t.length>100?'…':''}</p><button type="button">移除</button>`;d.querySelector('button').onclick=()=>{save(KEY.f,store(KEY.f).filter(id=>id!==rid(x)));renderSaved()};f.append(d)})}
function buildLaws(){const m=new Map;S.records.forEach(x=>{const k=`${x.n}|${x.v||''}`;if(!m.has(k))m.set(k,{name:x.n,version:x.v,department:x.d,published:x.p,items:[]});m.get(k).items.push(x)});S.laws=[...m.values()].sort((a,b)=>b.items.length-a.items.length||a.name.localeCompare(b.name,'zh-CN'))}
function renderLaws(q=''){q=q.trim();const a=S.laws.filter(x=>!q||x.name.includes(q)||x.department.includes(q));E.lawList.innerHTML='';$('#lawCount').textContent=`${a.length} 个文件版本`;a.slice(0,24).forEach(l=>{const b=document.createElement('button');b.type='button';b.className='law-card';b.innerHTML=`<span>${esc(l.department)}</span><strong>《${esc(l.name)}》</strong><small>${l.items.length} 条 · 版本 ${esc(l.version||'未标注')}</small>`;b.onclick=()=>openLaw(l);E.lawList.append(b)});if(a.length>24)E.lawList.insertAdjacentHTML('beforeend',`<p class="list-note">另有 ${a.length-24} 个结果，请输入名称缩小范围。</p>`)}
function openLaw(l){$('#lawDialogTitle').textContent=`《${l.name}》`;$('#lawDialogMeta').textContent=`${l.department} · ${l.items.length} 条 · ${l.published} · 版本 ${l.version||'未标注'}`;const draw=q=>{const a=l.items.filter(x=>!q||x.a.includes(q)||x.t.includes(q)||x.c.includes(q));$('#articleList').innerHTML='';a.slice(0,80).forEach(x=>$('#articleList').insertAdjacentHTML('beforeend',`<article><h3>${esc(x.a)} <small>${esc(x.c||'')}</small></h3><p>${highlight(x.t,q?[q]:[])}</p></article>`))};$('#articleSearch').value='';$('#articleSearch').oninput=e=>draw(e.target.value.trim());draw('');E.lawDialog.showModal()}
function dashboard(){const d=Object.entries(S.manifest.departments).sort((a,b)=>b[1]-a[1]),max=d[0]?.[1]||1,m=[['适用条文',S.records.length.toLocaleString('zh-CN')],['文件版本',S.manifest.documents],['法律部门',d.length],['本地可用','无需登录']];$('#metricGrid').innerHTML=m.map(([l,v])=>`<article><strong>${v}</strong><span>${l}</span></article>`).join('');$('#departmentBars').innerHTML=d.slice(0,10).map(([n,c])=>`<div><span>${esc(n)}</span><i><b style="width:${Math.max(2,c/max*100)}%"></b></i><em>${c.toLocaleString('zh-CN')}</em></div>`).join('')}

topics.forEach(([n,d,q],i)=>{const b=document.createElement('button');b.type='button';b.className='topic-card';b.innerHTML=`<span>0${i+1}</span><strong>${n}</strong><small>${d}</small>`;b.onclick=()=>{E.q.value=q;run(q)};$('#topicGrid').append(b)});
E.form.onsubmit=e=>{e.preventDefault();run(E.q.value,E.dept.value)};E.q.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();E.form.requestSubmit()}};document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{E.q.value=b.dataset.question;run(b.dataset.question,E.dept.value)});E.lawSearch.oninput=e=>renderLaws(e.target.value);$('#aboutButton').onclick=()=>$('#aboutDialog').showModal();$('#savedButton').onclick=()=>{renderSaved();E.savedDialog.showModal()};$('#lawDialogClose').onclick=()=>E.lawDialog.close();$('#savedDialogClose').onclick=()=>E.savedDialog.close();$('#clearHistory').onclick=()=>{save(KEY.h,[]);renderSaved()};
$('#copyButton').onclick=async()=>{const a=S.answer||{},lines=['初步结论',a.conclusion||'','','关键条件',...(a.conditions||[]).map(x=>`- ${x}`),'','建议步骤',...(a.actions||[]).map((x,i)=>`${i+1}. ${x}`),'','例外与边界',a.exceptions||'','',...S.hits.map(({item},i)=>`[${i+1}]《${item.n}》${item.a}\n${item.t}`),'','仅供个人学习与研究参考。'];await navigator.clipboard.writeText(lines.join('\n'));$('#copyButton').textContent='已复制';setTimeout(()=>$('#copyButton').textContent='复制摘要',1400)};
if(document.modelContext?.registerTool)document.modelContext.registerTool({name:'search_legal_provisions',title:'检索相关条文',description:'检索条文并返回结论、条件、行动建议、例外与依据。',inputSchema:{type:'object',properties:{question:{type:'string',minLength:2},department:{type:'string'}},required:['question'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async({question,department=''})=>{if(typeof question!=='string'||question.trim().length<2)throw new Error('问题至少需要两个字符');E.q.value=question;E.dept.value=department;return run(question,department)}});
})();
